// frontend-svelte/src/pages/NoteEditorPage.svelte
<script lang="ts">
  import { auth } from '../auth/auth.svelte';
  import { VersionConflictError, api } from '../api/client';
  import type { Note } from '../api/types';
  import { navigate } from '../lib/router';
  import MarkdownEditor from '../components/MarkdownEditor.svelte';
  import MarkdownView from '../components/MarkdownView.svelte';
  import ShareDialog from '../components/ShareDialog.svelte';
  import { extractMentionedUserIds } from '../utils/mentions';

  let { id }: { id?: string } = $props();
  const isNew = $derived(id === undefined);

  let note = $state<Note | null>(null);
  let title = $state('');
  let content = $state('');
  // Intentionally captures only the initial value: App.svelte keys this
  // component by the route id (`{#key id}`), so a changed id remounts it
  // instead of updating the prop in place.
  // svelte-ignore state_referenced_locally
  let loading = $state(id !== undefined);
  let saving = $state(false);
  let justSaved = $state(false);
  let error = $state<string | null>(null);
  let conflict = $state<Note | null>(null);
  let showShare = $state(false);

  $effect(() => {
    if (isNew || !id) return;
    loading = true;
    api
      .getNote(id)
      .then((n) => {
        note = n;
        title = n.title;
        content = n.contentMarkdown;
      })
      .catch((err: unknown) => {
        error = err instanceof Error ? err.message : 'Failed to load note';
      })
      .finally(() => {
        loading = false;
      });
  });

  $effect(() => {
    if (!justSaved) return;
    const timer = setTimeout(() => (justSaved = false), 3000);
    return () => clearTimeout(timer);
  });

  const readOnly = $derived(note !== null && note.myPermission === 'read');
  const canManageSharing = $derived(note?.myPermission === 'owner');
  const canDelete = $derived(note?.myPermission === 'owner');

  async function handleSave() {
    saving = true;
    error = null;
    conflict = null;
    justSaved = false;
    const mentionedUserIds = extractMentionedUserIds(content);
    try {
      if (isNew) {
        const created = await api.createNote({ title, contentMarkdown: content, mentionedUserIds });
        justSaved = true;
        navigate(`/notes/${created.id}`, { replace: true });
      } else if (note) {
        const updated = await api.updateNote(note.id, note.version, {
          title,
          contentMarkdown: content,
          mentionedUserIds,
        });
        note = updated;
        justSaved = true;
      }
    } catch (err) {
      if (err instanceof VersionConflictError) {
        conflict = err.currentNote;
      } else {
        error = err instanceof Error ? err.message : 'Failed to save note';
      }
    } finally {
      saving = false;
    }
  }

  async function handleDelete() {
    if (!note || !window.confirm('Delete this note? This cannot be undone.')) return;
    await api.deleteNote(note.id);
    navigate('/');
  }

  function reloadLatest() {
    if (!conflict) return;
    note = conflict;
    title = conflict.title;
    content = conflict.contentMarkdown;
    conflict = null;
  }
</script>

{#if !auth.loading && !auth.user}
  <div class="page">
    <p class="signin-prompt">You need to be signed in to {isNew ? 'create' : 'view'} this note.</p>
    <button type="button" class="btn" onclick={() => auth.login(window.location.pathname)}>Log in</button>
  </div>
{:else if loading}
  <p class="page">Loading…</p>
{:else if error}
  <p class="page text-danger">{error}</p>
{:else}
  <div class="page">
    {#if conflict}
      <div class="banner">
        <p>This note was changed by someone else since you opened it. Your unsaved edits are still below.</p>
        <button type="button" class="btn" onclick={reloadLatest}>
          Load the latest version (discards your changes)
        </button>
      </div>
    {/if}

    <input
      class="editor-title"
      value={title}
      oninput={(e) => {
        title = (e.currentTarget as HTMLInputElement).value;
        justSaved = false;
      }}
      placeholder="Untitled note"
      disabled={readOnly}
    />

    {#if readOnly}
      <MarkdownView markdown={content} />
    {:else}
      <MarkdownEditor
        value={content}
        onChange={(v) => {
          content = v;
          justSaved = false;
        }}
      />
    {/if}

    <div class="editor-actions">
      {#if !readOnly}
        <button type="button" class="btn btn-primary" onclick={handleSave} disabled={saving || title.trim() === ''}>
          {saving ? 'Saving…' : 'Save'}
        </button>
      {/if}
      {#if canManageSharing}
        <button type="button" class="btn" onclick={() => (showShare = true)}>Share</button>
      {/if}
      {#if canDelete}
        <button type="button" class="btn btn-danger" onclick={handleDelete}>Delete</button>
      {/if}
      {#if justSaved}
        <span role="status" class="save-status"><span aria-hidden="true">✓</span> Saved</span>
      {/if}
    </div>

    {#if showShare && note}
      <ShareDialog noteId={note.id} onClose={() => (showShare = false)} />
    {/if}
  </div>
{/if}

// frontend-vue/src/pages/NoteEditorPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAuth } from '../auth/auth';
import { VersionConflictError, api } from '../api/client';
import type { Note } from '../api/types';
import MarkdownEditor from '../components/MarkdownEditor.vue';
import MarkdownView from '../components/MarkdownView.vue';
import ShareDialog from '../components/ShareDialog.vue';
import { extractMentionedUserIds } from '../utils/mentions';

const props = defineProps<{ id?: string; isNew?: boolean }>();
const isNew = computed(() => props.isNew === true || props.id === undefined);

const router = useRouter();
const route = useRoute();
const { state: auth, login } = useAuth();

const note = ref<Note | null>(null);
const title = ref('');
const content = ref('');
const loading = ref(!isNew.value);
const saving = ref(false);
const justSaved = ref(false);
const error = ref<string | null>(null);
const conflict = ref<Note | null>(null);
const showShare = ref(false);

watch(
  () => props.id,
  (id) => {
    if (isNew.value || !id) return;
    loading.value = true;
    api
      .getNote(id)
      .then((n) => {
        note.value = n;
        title.value = n.title;
        content.value = n.contentMarkdown;
      })
      .catch((err: unknown) => {
        error.value = err instanceof Error ? err.message : 'Failed to load note';
      })
      .finally(() => {
        loading.value = false;
      });
  },
  { immediate: true },
);

let savedTimer: ReturnType<typeof setTimeout> | undefined;
watch(justSaved, (saved) => {
  clearTimeout(savedTimer);
  if (!saved) return;
  savedTimer = setTimeout(() => {
    justSaved.value = false;
  }, 3000);
});

const readOnly = computed(() => note.value !== null && note.value.myPermission === 'read');
const canManageSharing = computed(() => note.value?.myPermission === 'owner');
const canDelete = computed(() => note.value?.myPermission === 'owner');

function handleTitleInput(e: Event) {
  title.value = (e.target as HTMLInputElement).value;
  justSaved.value = false;
}

function handleContentChange(value: string) {
  content.value = value;
  justSaved.value = false;
}

async function handleSave() {
  saving.value = true;
  error.value = null;
  conflict.value = null;
  justSaved.value = false;
  const mentionedUserIds = extractMentionedUserIds(content.value);
  try {
    if (isNew.value) {
      const created = await api.createNote({ title: title.value, contentMarkdown: content.value, mentionedUserIds });
      justSaved.value = true;
      router.replace(`/notes/${created.id}`);
    } else if (note.value) {
      const updated = await api.updateNote(note.value.id, note.value.version, {
        title: title.value,
        contentMarkdown: content.value,
        mentionedUserIds,
      });
      note.value = updated;
      justSaved.value = true;
    }
  } catch (err) {
    if (err instanceof VersionConflictError) {
      conflict.value = err.currentNote;
    } else {
      error.value = err instanceof Error ? err.message : 'Failed to save note';
    }
  } finally {
    saving.value = false;
  }
}

async function handleDelete() {
  if (!note.value || !window.confirm('Delete this note? This cannot be undone.')) return;
  await api.deleteNote(note.value.id);
  router.push('/');
}

function reloadLatest() {
  if (!conflict.value) return;
  note.value = conflict.value;
  title.value = conflict.value.title;
  content.value = conflict.value.contentMarkdown;
  conflict.value = null;
}
</script>

<template>
  <div v-if="!auth.loading && !auth.user" class="page">
    <p class="signin-prompt">You need to be signed in to {{ isNew ? 'create' : 'view' }} this note.</p>
    <button type="button" class="btn" @click="login(route.fullPath)">Log in</button>
  </div>
  <p v-else-if="loading" class="page">Loading…</p>
  <p v-else-if="error" class="page text-danger">{{ error }}</p>
  <div v-else class="page">
    <div v-if="conflict" class="banner">
      <p>This note was changed by someone else since you opened it. Your unsaved edits are still below.</p>
      <button type="button" class="btn" @click="reloadLatest">
        Load the latest version (discards your changes)
      </button>
    </div>

    <input
      class="editor-title"
      :value="title"
      placeholder="Untitled note"
      :disabled="readOnly"
      @input="handleTitleInput"
    />

    <MarkdownView v-if="readOnly" :markdown="content" />
    <MarkdownEditor v-else :model-value="content" @update:model-value="handleContentChange" />

    <div class="editor-actions">
      <button
        v-if="!readOnly"
        type="button"
        class="btn btn-primary"
        :disabled="saving || title.trim() === ''"
        @click="handleSave"
      >
        {{ saving ? 'Saving…' : 'Save' }}
      </button>
      <button v-if="canManageSharing" type="button" class="btn" @click="showShare = true">Share</button>
      <button v-if="canDelete" type="button" class="btn btn-danger" @click="handleDelete">Delete</button>
      <span v-if="justSaved" role="status" class="save-status">
        <span aria-hidden="true">✓</span> Saved
      </span>
    </div>

    <ShareDialog v-if="showShare && note" :note-id="note.id" @close="showShare = false" />
  </div>
</template>
