// frontend-react/src/pages/NoteEditorPage.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/useAuth';
import { VersionConflictError, api } from '../api/client';
import type { Note } from '../api/types';
import { MarkdownEditor } from '../components/MarkdownEditor';
import { MarkdownView } from '../components/MarkdownView';
import { ShareDialog } from '../components/ShareDialog';
import { extractMentionedUserIds } from '../utils/mentions';

export function NoteEditorPage() {
  const { id } = useParams<{ id: string }>();
  const isNew = id === undefined;
  const navigate = useNavigate();
  const { user, loading: authLoading, login } = useAuth();

  const [note, setNote] = useState<Note | null>(null);
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(!isNew);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [conflict, setConflict] = useState<Note | null>(null);
  const [showShare, setShowShare] = useState(false);

  useEffect(() => {
    if (isNew || !id) return;
    setLoading(true);
    api
      .getNote(id)
      .then((n) => {
        setNote(n);
        setTitle(n.title);
        setContent(n.contentMarkdown);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'Failed to load note'))
      .finally(() => setLoading(false));
  }, [id, isNew]);

  if (!authLoading && !user) {
    return (
      <div className="page">
        <p>You need to be signed in to {isNew ? 'create' : 'view'} this note.</p>
        <button type="button" onClick={() => login(window.location.pathname)}>
          Log in
        </button>
      </div>
    );
  }

  if (loading) return <p className="page">Loading…</p>;
  if (error) return <p className="page error-banner">{error}</p>;

  const readOnly = note !== null && note.myPermission === 'read';
  const canManageSharing = note?.myPermission === 'owner';
  const canDelete = note?.myPermission === 'owner';

  async function handleSave() {
    setSaving(true);
    setError(null);
    setConflict(null);
    const mentionedUserIds = extractMentionedUserIds(content);
    try {
      if (isNew) {
        const created = await api.createNote({ title, contentMarkdown: content, mentionedUserIds });
        navigate(`/notes/${created.id}`, { replace: true });
      } else if (note) {
        const updated = await api.updateNote(note.id, note.version, {
          title,
          contentMarkdown: content,
          mentionedUserIds,
        });
        setNote(updated);
      }
    } catch (err) {
      if (err instanceof VersionConflictError) {
        setConflict(err.currentNote);
      } else {
        setError(err instanceof Error ? err.message : 'Failed to save note');
      }
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete() {
    if (!note || !window.confirm('Delete this note? This cannot be undone.')) return;
    await api.deleteNote(note.id);
    navigate('/');
  }

  function reloadLatest() {
    if (!conflict) return;
    setNote(conflict);
    setTitle(conflict.title);
    setContent(conflict.contentMarkdown);
    setConflict(null);
  }

  return (
    <div className="page note-editor-page">
      {conflict && (
        <div className="conflict-banner">
          <p>This note was changed by someone else since you opened it. Your unsaved edits are still below.</p>
          <button type="button" onClick={reloadLatest}>
            Load the latest version (discards your changes)
          </button>
        </div>
      )}

      <input
        className="note-editor-page__title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Untitled note"
        disabled={readOnly}
      />

      {readOnly ? <MarkdownView markdown={content} /> : <MarkdownEditor value={content} onChange={setContent} />}

      <div className="note-editor-page__actions">
        {!readOnly && (
          <button type="button" onClick={handleSave} disabled={saving || title.trim() === ''}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        )}
        {canManageSharing && (
          <button type="button" onClick={() => setShowShare(true)}>
            Share
          </button>
        )}
        {canDelete && (
          <button type="button" onClick={handleDelete} className="danger">
            Delete
          </button>
        )}
      </div>

      {showShare && note && <ShareDialog noteId={note.id} onClose={() => setShowShare(false)} />}
    </div>
  );
}

// frontend-svelte/src/pages/NoteEditorPage.svelte
<script lang="ts">
  import { auth } from '../auth/auth.svelte';
  import { VersionConflictError, api } from '../api/client';
  import type { Note } from '../api/types';
  import { navigate } from '../lib/router';
  import MarkdownEditor from '../components/MarkdownEditor.svelte';
  import MarkdownView from '../components/MarkdownView.svelte';
  import ShareDialog from '../components/ShareDialog.svelte';
  import { extractMentionedUserIds } from '../utils/mentions';

  let { id }: { id?: string } = $props();
  const isNew = $derived(id === undefined);

  let note = $state<Note | null>(null);
  let title = $state('');
  let content = $state('');
  // Intentionally captures only the initial value: App.svelte keys this
  // component by the route id (`{#key id}`), so a changed id remounts it
  // instead of updating the prop in place.
  // svelte-ignore state_referenced_locally
  let loading = $state(id !== undefined);
  let saving = $state(false);
  let justSaved = $state(false);
  let error = $state<string | null>(null);
  let conflict = $state<Note | null>(null);
  let showShare = $state(false);

  $effect(() => {
    if (isNew || !id) return;
    loading = true;
    api
      .getNote(id)
      .then((n) => {
        note = n;
        title = n.title;
        content = n.contentMarkdown;
      })
      .catch((err: unknown) => {
        error = err instanceof Error ? err.message : 'Failed to load note';
      })
      .finally(() => {
        loading = false;
      });
  });

  $effect(() => {
    if (!justSaved) return;
    const timer = setTimeout(() => (justSaved = false), 3000);
    return () => clearTimeout(timer);
  });

  const readOnly = $derived(note !== null && note.myPermission === 'read');
  const canManageSharing = $derived(note?.myPermission === 'owner');
  const canDelete = $derived(note?.myPermission === 'owner');

  async function handleSave() {
    saving = true;
    error = null;
    conflict = null;
    justSaved = false;
    const mentionedUserIds = extractMentionedUserIds(content);
    try {
      if (isNew) {
        const created = await api.createNote({ title, contentMarkdown: content, mentionedUserIds });
        justSaved = true;
        navigate(`/notes/${created.id}`, { replace: true });
      } else if (note) {
        const updated = await api.updateNote(note.id, note.version, {
          title,
          contentMarkdown: content,
          mentionedUserIds,
        });
        note = updated;
        justSaved = true;
      }
    } catch (err) {
      if (err instanceof VersionConflictError) {
        conflict = err.currentNote;
      } else {
        error = err instanceof Error ? err.message : 'Failed to save note';
      }
    } finally {
      saving = false;
    }
  }

  async function handleDelete() {
    if (!note || !window.confirm('Delete this note? This cannot be undone.')) return;
    await api.deleteNote(note.id);
    navigate('/');
  }

  function reloadLatest() {
    if (!conflict) return;
    note = conflict;
    title = conflict.title;
    content = conflict.contentMarkdown;
    conflict = null;
  }
</script>

{#if !auth.loading && !auth.user}
  <div class="page">
    <p class="signin-prompt">You need to be signed in to {isNew ? 'create' : 'view'} this note.</p>
    <button type="button" class="btn" onclick={() => auth.login(window.location.pathname)}>Log in</button>
  </div>
{:else if loading}
  <p class="page">Loading…</p>
{:else if error}
  <p class="page text-danger">{error}</p>
{:else}
  <div class="page">
    {#if conflict}
      <div class="banner">
        <p>This note was changed by someone else since you opened it. Your unsaved edits are still below.</p>
        <button type="button" class="btn" onclick={reloadLatest}>
          Load the latest version (discards your changes)
        </button>
      </div>
    {/if}

    <input
      class="editor-title"
      value={title}
      oninput={(e) => {
        title = (e.currentTarget as HTMLInputElement).value;
        justSaved = false;
      }}
      placeholder="Untitled note"
      disabled={readOnly}
    />

    {#if readOnly}
      <MarkdownView markdown={content} />
    {:else}
      <MarkdownEditor
        value={content}
        onChange={(v) => {
          content = v;
          justSaved = false;
        }}
      />
    {/if}

    <div class="editor-actions">
      {#if !readOnly}
        <button type="button" class="btn btn-primary" onclick={handleSave} disabled={saving || title.trim() === ''}>
          {saving ? 'Saving…' : 'Save'}
        </button>
      {/if}
      {#if canManageSharing}
        <button type="button" class="btn" onclick={() => (showShare = true)}>Share</button>
      {/if}
      {#if canDelete}
        <button type="button" class="btn btn-danger" onclick={handleDelete}>Delete</button>
      {/if}
      {#if justSaved}
        <span role="status" class="save-status"><span aria-hidden="true">✓</span> Saved</span>
      {/if}
    </div>

    {#if showShare && note}
      <ShareDialog noteId={note.id} onClose={() => (showShare = false)} />
    {/if}
  </div>
{/if}
