// frontend-svelte/src/pages/PublicNotePage.svelte
<script lang="ts">
  import { api } from '../api/client';
  import type { PublicNoteView } from '../api/types';
  import MarkdownView from '../components/MarkdownView.svelte';

  let { token }: { token: string } = $props();

  let note = $state<PublicNoteView | null>(null);
  let error = $state<string | null>(null);

  $effect(() => {
    api
      .getPublicNote(token)
      .then((n) => (note = n))
      .catch(() => {
        error = 'This note is not available. The link may have been revoked.';
      });
  });
</script>

{#if error}
  <div class="page">
    <p class="text-danger">{error}</p>
  </div>
{:else if !note}
  <div class="page">
    <p>Loading…</p>
  </div>
{:else}
  <div class="page">
    <p class="public-pill">Shared read-only note</p>
    <h1 class="public-note-title">{note.title}</h1>
    <MarkdownView markdown={note.contentMarkdown} />
  </div>
{/if}

// frontend-angular/src/app/pages/public-note-page/public-note-page.ts
import { Component, effect, inject, input, signal } from '@angular/core';
import { Api } from '../../api/api';
import type { PublicNoteView } from '../../api/types';
import { MarkdownView } from '../../components/markdown-view/markdown-view';

@Component({
  selector: 'app-public-note-page',
  imports: [MarkdownView],
  templateUrl: './public-note-page.html',
  styleUrl: './public-note-page.css',
})
export class PublicNotePage {
  private readonly api = inject(Api);

  readonly token = input<string>();

  protected readonly note = signal<PublicNoteView | null>(null);
  protected readonly error = signal<string | null>(null);

  constructor() {
    effect(() => {
      const token = this.token();
      if (!token) return;
      this.api
        .getPublicNote(token)
        .then((n) => this.note.set(n))
        .catch(() => this.error.set('This note is not available. The link may have been revoked.'));
    });
  }
}
