// frontend-angular/src/app/pages/note-editor-page/note-editor-page.ts
import { Component, computed, effect, inject, input, signal } from '@angular/core';
import { Router } from '@angular/router';
import { Api, VersionConflictError } from '../../api/api';
import type { Note } from '../../api/types';
import { Auth } from '../../auth/auth';
import { MarkdownEditor } from '../../components/markdown-editor/markdown-editor';
import { MarkdownView } from '../../components/markdown-view/markdown-view';
import { ShareDialog } from '../../components/share-dialog/share-dialog';
import { extractMentionedUserIds } from '../../utils/mentions';

// `id` is bound straight from the `:id` route param via the router's
// component-input-binding feature (see app.routes.ts / app.config.ts) —
// undefined on `/notes/new`, which is how this page tells "new" from
// "edit" apart, same as frontend-react's `useParams` check.
@Component({
  selector: 'app-note-editor-page',
  imports: [MarkdownEditor, MarkdownView, ShareDialog],
  templateUrl: './note-editor-page.html',
  styleUrl: './note-editor-page.css',
})
export class NoteEditorPage {
  private readonly api = inject(Api);
  private readonly router = inject(Router);
  protected readonly auth = inject(Auth);

  readonly id = input<string>();
  protected readonly isNew = computed(() => this.id() === undefined);

  protected readonly note = signal<Note | null>(null);
  protected readonly title = signal('');
  protected readonly content = signal('');
  protected readonly loading = signal(false);
  protected readonly saving = signal(false);
  protected readonly justSaved = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly conflict = signal<Note | null>(null);
  protected readonly showShare = signal(false);

  protected readonly readOnly = computed(() => this.note()?.myPermission === 'read');
  protected readonly canManageSharing = computed(() => this.note()?.myPermission === 'owner');
  protected readonly canDelete = computed(() => this.note()?.myPermission === 'owner');

  constructor() {
    effect(() => {
      const id = this.id();
      if (id !== undefined) this.loadNote(id);
    });

    effect((onCleanup) => {
      if (!this.justSaved()) return;
      const timer = setTimeout(() => this.justSaved.set(false), 3000);
      onCleanup(() => clearTimeout(timer));
    });
  }

  private async loadNote(id: string): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      const n = await this.api.getNote(id);
      this.note.set(n);
      this.title.set(n.title);
      this.content.set(n.contentMarkdown);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : 'Failed to load note');
    } finally {
      this.loading.set(false);
    }
  }

  protected onTitleInput(value: string): void {
    this.title.set(value);
    this.justSaved.set(false);
  }

  protected onContentChange(value: string): void {
    this.content.set(value);
    this.justSaved.set(false);
  }

  protected async handleSave(): Promise<void> {
    this.saving.set(true);
    this.error.set(null);
    this.conflict.set(null);
    this.justSaved.set(false);
    const mentionedUserIds = extractMentionedUserIds(this.content());
    try {
      if (this.isNew()) {
        const created = await this.api.createNote({
          title: this.title(),
          contentMarkdown: this.content(),
          mentionedUserIds,
        });
        this.justSaved.set(true);
        this.router.navigate(['/notes', created.id], { replaceUrl: true });
      } else {
        const current = this.note();
        if (!current) return;
        const updated = await this.api.updateNote(current.id, current.version, {
          title: this.title(),
          contentMarkdown: this.content(),
          mentionedUserIds,
        });
        this.note.set(updated);
        this.justSaved.set(true);
      }
    } catch (err) {
      if (err instanceof VersionConflictError) {
        this.conflict.set(err.currentNote);
      } else {
        this.error.set(err instanceof Error ? err.message : 'Failed to save note');
      }
    } finally {
      this.saving.set(false);
    }
  }

  protected async handleDelete(): Promise<void> {
    const current = this.note();
    if (!current || !window.confirm('Delete this note? This cannot be undone.')) return;
    await this.api.deleteNote(current.id);
    this.router.navigateByUrl('/');
  }

  protected reloadLatest(): void {
    const latest = this.conflict();
    if (!latest) return;
    this.note.set(latest);
    this.title.set(latest.title);
    this.content.set(latest.contentMarkdown);
    this.conflict.set(null);
  }

  protected login(): void {
    this.auth.login(window.location.pathname);
  }
}

// frontend-react/src/pages/NoteEditorPage.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/useAuth';
import { VersionConflictError, api } from '../api/client';
import type { Note } from '../api/types';
import { MarkdownEditor } from '../components/MarkdownEditor';
import { MarkdownView } from '../components/MarkdownView';
import { ShareDialog } from '../components/ShareDialog';
import { extractMentionedUserIds } from '../utils/mentions';

export function NoteEditorPage() {
  const { id } = useParams<{ id: string }>();
  const isNew = id === undefined;
  const navigate = useNavigate();
  const { user, loading: authLoading, login } = useAuth();

  const [note, setNote] = useState<Note | null>(null);
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(!isNew);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [conflict, setConflict] = useState<Note | null>(null);
  const [showShare, setShowShare] = useState(false);

  useEffect(() => {
    if (isNew || !id) return;
    setLoading(true);
    api
      .getNote(id)
      .then((n) => {
        setNote(n);
        setTitle(n.title);
        setContent(n.contentMarkdown);
      })
      .catch((err: unknown) => setError(err instanceof Error ? err.message : 'Failed to load note'))
      .finally(() => setLoading(false));
  }, [id, isNew]);

  if (!authLoading && !user) {
    return (
      <div className="page">
        <p>You need to be signed in to {isNew ? 'create' : 'view'} this note.</p>
        <button type="button" onClick={() => login(window.location.pathname)}>
          Log in
        </button>
      </div>
    );
  }

  if (loading) return <p className="page">Loading…</p>;
  if (error) return <p className="page error-banner">{error}</p>;

  const readOnly = note !== null && note.myPermission === 'read';
  const canManageSharing = note?.myPermission === 'owner';
  const canDelete = note?.myPermission === 'owner';

  async function handleSave() {
    setSaving(true);
    setError(null);
    setConflict(null);
    const mentionedUserIds = extractMentionedUserIds(content);
    try {
      if (isNew) {
        const created = await api.createNote({ title, contentMarkdown: content, mentionedUserIds });
        navigate(`/notes/${created.id}`, { replace: true });
      } else if (note) {
        const updated = await api.updateNote(note.id, note.version, {
          title,
          contentMarkdown: content,
          mentionedUserIds,
        });
        setNote(updated);
      }
    } catch (err) {
      if (err instanceof VersionConflictError) {
        setConflict(err.currentNote);
      } else {
        setError(err instanceof Error ? err.message : 'Failed to save note');
      }
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete() {
    if (!note || !window.confirm('Delete this note? This cannot be undone.')) return;
    await api.deleteNote(note.id);
    navigate('/');
  }

  function reloadLatest() {
    if (!conflict) return;
    setNote(conflict);
    setTitle(conflict.title);
    setContent(conflict.contentMarkdown);
    setConflict(null);
  }

  return (
    <div className="page note-editor-page">
      {conflict && (
        <div className="conflict-banner">
          <p>This note was changed by someone else since you opened it. Your unsaved edits are still below.</p>
          <button type="button" onClick={reloadLatest}>
            Load the latest version (discards your changes)
          </button>
        </div>
      )}

      <input
        className="note-editor-page__title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Untitled note"
        disabled={readOnly}
      />

      {readOnly ? <MarkdownView markdown={content} /> : <MarkdownEditor value={content} onChange={setContent} />}

      <div className="note-editor-page__actions">
        {!readOnly && (
          <button type="button" onClick={handleSave} disabled={saving || title.trim() === ''}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        )}
        {canManageSharing && (
          <button type="button" onClick={() => setShowShare(true)}>
            Share
          </button>
        )}
        {canDelete && (
          <button type="button" onClick={handleDelete} className="danger">
            Delete
          </button>
        )}
      </div>

      {showShare && note && <ShareDialog noteId={note.id} onClose={() => setShowShare(false)} />}
    </div>
  );
}
