// frontend-vue/src/components/NotePreview.vue
<template>
  <div class="note-preview" aria-hidden="true">
    <h3>Welcome to Notes</h3>
    <p>
      This is what a note looks like. Log in to write your own, format them with Markdown, share
      them with teammates, and mention people with @username.
    </p>
    <div class="note-card-meta">
      <span>Example</span>
      <span>Public</span>
      <time>Today</time>
    </div>
  </div>
</template>

// frontend-svelte/src/components/NotePreview.svelte
<div class="note-preview" aria-hidden="true">
  <h3>Welcome to Notes</h3>
  <p>
    This is what a note looks like. Log in to write your own, format them with Markdown, share
    them with teammates, and mention people with @username.
  </p>
  <div class="note-card-meta">
    <span>Example</span>
    <span>Public</span>
    <time>Today</time>
  </div>
</div>
