// frontend-vue/src/components/NoteGrid.vue
<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
import { useNoteFeed } from '../composables/useNoteFeed';
import NoteCard from './NoteCard.vue';

const { notes, loading, hasMore, error, loadMore } = useNoteFeed();

const sentinelRef = ref<HTMLDivElement | null>(null);
let observer: IntersectionObserver | null = null;

watch(
  [sentinelRef, hasMore],
  ([sentinel, more]) => {
    observer?.disconnect();
    if (!sentinel || !more) return;
    observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) loadMore();
      },
      { rootMargin: '200px' },
    );
    observer.observe(sentinel);
  },
  { immediate: true },
);

onBeforeUnmount(() => observer?.disconnect());
</script>

<template>
  <p v-if="error" class="text-danger">{{ error }}</p>
  <template v-else>
    <div class="note-grid">
      <NoteCard v-for="note in notes" :key="note.id" :note="note" />
    </div>
    <p v-if="loading" class="feed-status">Loading…</p>
    <p v-if="!loading && notes.length === 0" class="feed-status">No notes yet.</p>
    <div ref="sentinelRef" />
  </template>
</template>

// frontend-svelte/src/components/NoteGrid.svelte
<script lang="ts">
  import { createNoteFeed } from '../hooks/noteFeed.svelte';
  import NoteCard from './NoteCard.svelte';

  const feed = createNoteFeed();

  let sentinelEl: HTMLDivElement | undefined = $state();

  $effect(() => {
    const sentinel = sentinelEl;
    if (!sentinel || !feed.hasMore) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) feed.loadMore();
      },
      { rootMargin: '200px' },
    );
    observer.observe(sentinel);
    return () => observer.disconnect();
  });
</script>

{#if feed.error}
  <p class="text-danger">{feed.error}</p>
{:else}
  <div class="note-grid">
    {#each feed.notes as note (note.id)}
      <NoteCard {note} />
    {/each}
  </div>
  {#if feed.loading}
    <p class="feed-status">Loading…</p>
  {/if}
  {#if !feed.loading && feed.notes.length === 0}
    <p class="feed-status">No notes yet.</p>
  {/if}
  <div bind:this={sentinelEl}></div>
{/if}
